/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CameraApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class CameraApiTests
    {
        private CameraApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new CameraApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CameraApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' CameraApi
            //Assert.IsInstanceOfType(typeof(CameraApi), instance, "instance is a CameraApi");
        }

        /// <summary>
        /// Test CameraSetOriginOrientationPut
        /// </summary>
        [Test]
        public void CameraSetOriginOrientationPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Orientation body = null;
            //instance.CameraSetOriginOrientationPut(body);
            
        }
        /// <summary>
        /// Test CameraStateGet
        /// </summary>
        [Test]
        public void CameraStateGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CameraStateGet();
            //Assert.IsInstanceOf<CameraState> (response, "response is CameraState");
        }
        /// <summary>
        /// Test CameraStatePut
        /// </summary>
        [Test]
        public void CameraStatePutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CameraState body = null;
            //instance.CameraStatePut(body);
            
        }
    }

}
