/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Color
    /// </summary>
    [DataContract]
        public partial class Color :  IEquatable<Color>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Color" /> class.
        /// </summary>
        /// <param name="r">Red [0-255] (required).</param>
        /// <param name="g">Green [0-255] (required).</param>
        /// <param name="b">Blue [0-255] (required).</param>
        /// <param name="a">Alpha [0-255].</param>
        public Color(int? r = default(int?), int? g = default(int?), int? b = default(int?), int? a = default(int?))
        {
            // to ensure "r" is required (not null)
            if (r == null)
            {
                throw new InvalidDataException("r is a required property for Color and cannot be null");
            }
            else
            {
                this.R = r;
            }
            // to ensure "g" is required (not null)
            if (g == null)
            {
                throw new InvalidDataException("g is a required property for Color and cannot be null");
            }
            else
            {
                this.G = g;
            }
            // to ensure "b" is required (not null)
            if (b == null)
            {
                throw new InvalidDataException("b is a required property for Color and cannot be null");
            }
            else
            {
                this.B = b;
            }
            this.A = a;
        }
        
        /// <summary>
        /// Red [0-255]
        /// </summary>
        /// <value>Red [0-255]</value>
        [DataMember(Name="r", EmitDefaultValue=false)]
        public int? R { get; set; }

        /// <summary>
        /// Green [0-255]
        /// </summary>
        /// <value>Green [0-255]</value>
        [DataMember(Name="g", EmitDefaultValue=false)]
        public int? G { get; set; }

        /// <summary>
        /// Blue [0-255]
        /// </summary>
        /// <value>Blue [0-255]</value>
        [DataMember(Name="b", EmitDefaultValue=false)]
        public int? B { get; set; }

        /// <summary>
        /// Alpha [0-255]
        /// </summary>
        /// <value>Alpha [0-255]</value>
        [DataMember(Name="a", EmitDefaultValue=false)]
        public int? A { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Color {\n");
            sb.Append("  R: ").Append(R).Append("\n");
            sb.Append("  G: ").Append(G).Append("\n");
            sb.Append("  B: ").Append(B).Append("\n");
            sb.Append("  A: ").Append(A).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Color);
        }

        /// <summary>
        /// Returns true if Color instances are equal
        /// </summary>
        /// <param name="input">Instance of Color to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Color input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.R == input.R ||
                    (this.R != null &&
                    this.R.Equals(input.R))
                ) && 
                (
                    this.G == input.G ||
                    (this.G != null &&
                    this.G.Equals(input.G))
                ) && 
                (
                    this.B == input.B ||
                    (this.B != null &&
                    this.B.Equals(input.B))
                ) && 
                (
                    this.A == input.A ||
                    (this.A != null &&
                    this.A.Equals(input.A))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.R != null)
                    hashCode = hashCode * 59 + this.R.GetHashCode();
                if (this.G != null)
                    hashCode = hashCode * 59 + this.G.GetHashCode();
                if (this.B != null)
                    hashCode = hashCode * 59 + this.B.GetHashCode();
                if (this.A != null)
                    hashCode = hashCode * 59 + this.A.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
