/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines DetectionClasses
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DetectionClasses
    {
        /// <summary>
        /// Enum Connection for value: Connection
        /// </summary>
        [EnumMember(Value = "Connection")]
        Connection = 1,
        /// <summary>
        /// Enum Crack for value: Crack
        /// </summary>
        [EnumMember(Value = "Crack")]
        Crack = 2,
        /// <summary>
        /// Enum Root for value: Root
        /// </summary>
        [EnumMember(Value = "Root")]
        Root = 3,
        /// <summary>
        /// Enum AdhesiveSubstances for value: AdhesiveSubstances
        /// </summary>
        [EnumMember(Value = "AdhesiveSubstances")]
        AdhesiveSubstances = 4,
        /// <summary>
        /// Enum SurfaceDamage for value: SurfaceDamage
        /// </summary>
        [EnumMember(Value = "SurfaceDamage")]
        SurfaceDamage = 5    }
}
