/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FrameTime
    /// </summary>
    [DataContract]
        public partial class FrameTime :  IEquatable<FrameTime>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FrameTime" /> class.
        /// </summary>
        /// <param name="time">UTM.</param>
        /// <param name="frameNo">frameNo.</param>
        public FrameTime(DateTime? time = default(DateTime?), int? frameNo = default(int?))
        {
            this.Time = time;
            this.FrameNo = frameNo;
        }
        
        /// <summary>
        /// UTM
        /// </summary>
        /// <value>UTM</value>
        [DataMember(Name="time", EmitDefaultValue=false)]
        public DateTime? Time { get; set; }

        /// <summary>
        /// Gets or Sets FrameNo
        /// </summary>
        [DataMember(Name="frameNo", EmitDefaultValue=false)]
        public int? FrameNo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FrameTime {\n");
            sb.Append("  Time: ").Append(Time).Append("\n");
            sb.Append("  FrameNo: ").Append(FrameNo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FrameTime);
        }

        /// <summary>
        /// Returns true if FrameTime instances are equal
        /// </summary>
        /// <param name="input">Instance of FrameTime to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FrameTime input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Time == input.Time ||
                    (this.Time != null &&
                    this.Time.Equals(input.Time))
                ) && 
                (
                    this.FrameNo == input.FrameNo ||
                    (this.FrameNo != null &&
                    this.FrameNo.Equals(input.FrameNo))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Time != null)
                    hashCode = hashCode * 59 + this.Time.GetHashCode();
                if (this.FrameNo != null)
                    hashCode = hashCode * 59 + this.FrameNo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
