/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// InspectionNorm
    /// </summary>
    [DataContract]
        public partial class InspectionNorm :  IEquatable<InspectionNorm>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InspectionNorm" /> class.
        /// </summary>
        /// <param name="exchangeFormat">exchangeFormat.</param>
        /// <param name="codeSystem">codeSystem.</param>
        public InspectionNorm(string exchangeFormat = default(string), string codeSystem = default(string))
        {
            this.ExchangeFormat = exchangeFormat;
            this.CodeSystem = codeSystem;
        }
        
        /// <summary>
        /// Gets or Sets ExchangeFormat
        /// </summary>
        [DataMember(Name="exchangeFormat", EmitDefaultValue=false)]
        public string ExchangeFormat { get; set; }

        /// <summary>
        /// Gets or Sets CodeSystem
        /// </summary>
        [DataMember(Name="codeSystem", EmitDefaultValue=false)]
        public string CodeSystem { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InspectionNorm {\n");
            sb.Append("  ExchangeFormat: ").Append(ExchangeFormat).Append("\n");
            sb.Append("  CodeSystem: ").Append(CodeSystem).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InspectionNorm);
        }

        /// <summary>
        /// Returns true if InspectionNorm instances are equal
        /// </summary>
        /// <param name="input">Instance of InspectionNorm to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InspectionNorm input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ExchangeFormat == input.ExchangeFormat ||
                    (this.ExchangeFormat != null &&
                    this.ExchangeFormat.Equals(input.ExchangeFormat))
                ) && 
                (
                    this.CodeSystem == input.CodeSystem ||
                    (this.CodeSystem != null &&
                    this.CodeSystem.Equals(input.CodeSystem))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ExchangeFormat != null)
                    hashCode = hashCode * 59 + this.ExchangeFormat.GetHashCode();
                if (this.CodeSystem != null)
                    hashCode = hashCode * 59 + this.CodeSystem.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
