/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines PipeProfiles
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum PipeProfiles
    {
        /// <summary>
        /// Enum CircleProfile for value: CircleProfile
        /// </summary>
        [EnumMember(Value = "CircleProfile")]
        CircleProfile = 1,
        /// <summary>
        /// Enum RectangleProfile for value: RectangleProfile
        /// </summary>
        [EnumMember(Value = "RectangleProfile")]
        RectangleProfile = 2,
        /// <summary>
        /// Enum EggProfile for value: EggProfile
        /// </summary>
        [EnumMember(Value = "EggProfile")]
        EggProfile = 3,
        /// <summary>
        /// Enum MouthProfile for value: MouthProfile
        /// </summary>
        [EnumMember(Value = "MouthProfile")]
        MouthProfile = 4,
        /// <summary>
        /// Enum TrapezoidProfile for value: TrapezoidProfile
        /// </summary>
        [EnumMember(Value = "TrapezoidProfile")]
        TrapezoidProfile = 5,
        /// <summary>
        /// Enum DoubleTrapezoidProfile for value: DoubleTrapezoidProfile
        /// </summary>
        [EnumMember(Value = "DoubleTrapezoidProfile")]
        DoubleTrapezoidProfile = 6,
        /// <summary>
        /// Enum Other for value: Other
        /// </summary>
        [EnumMember(Value = "Other")]
        Other = 7    }
}
