/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines RunningStates
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum RunningStates
    {
        /// <summary>
        /// Enum Run for value: Run
        /// </summary>
        [EnumMember(Value = "Run")]
        Run = 1,
        /// <summary>
        /// Enum Pause for value: Pause
        /// </summary>
        [EnumMember(Value = "Pause")]
        Pause = 2,
        /// <summary>
        /// Enum Stop for value: Stop
        /// </summary>
        [EnumMember(Value = "Stop")]
        Stop = 3    }
}
