/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// WebHookProperties
    /// </summary>
    [DataContract]
        public partial class WebHookProperties :  IEquatable<WebHookProperties>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebHookProperties" /> class.
        /// </summary>
        /// <param name="serviceURI">&#x27;The service URI for the webhook to post notifications.&#x27; &#x27;(e.g.: http://127.0.0.1:8080/uri/webHookReceiver)&#x27;  (required).</param>
        public WebHookProperties(string serviceURI = default(string))
        {
            // to ensure "serviceURI" is required (not null)
            if (serviceURI == null)
            {
                throw new InvalidDataException("serviceURI is a required property for WebHookProperties and cannot be null");
            }
            else
            {
                this.ServiceURI = serviceURI;
            }
        }
        
        /// <summary>
        /// &#x27;The service URI for the webhook to post notifications.&#x27; &#x27;(e.g.: http://127.0.0.1:8080/uri/webHookReceiver)&#x27; 
        /// </summary>
        /// <value>&#x27;The service URI for the webhook to post notifications.&#x27; &#x27;(e.g.: http://127.0.0.1:8080/uri/webHookReceiver)&#x27; </value>
        [DataMember(Name="serviceURI", EmitDefaultValue=false)]
        public string ServiceURI { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class WebHookProperties {\n");
            sb.Append("  ServiceURI: ").Append(ServiceURI).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WebHookProperties);
        }

        /// <summary>
        /// Returns true if WebHookProperties instances are equal
        /// </summary>
        /// <param name="input">Instance of WebHookProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WebHookProperties input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ServiceURI == input.ServiceURI ||
                    (this.ServiceURI != null &&
                    this.ServiceURI.Equals(input.ServiceURI))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ServiceURI != null)
                    hashCode = hashCode * 59 + this.ServiceURI.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
