/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CameraState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CameraStateTests
    {
        // TODO uncomment below to declare an instance variable for CameraState
        //private CameraState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CameraState
            //instance = new CameraState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CameraState
        /// </summary>
        [Test]
        public void CameraStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CameraState
            //Assert.IsInstanceOfType<CameraState> (instance, "variable 'instance' is a CameraState");
        }


        /// <summary>
        /// Test the property 'FrameTime'
        /// </summary>
        [Test]
        public void FrameTimeTest()
        {
            // TODO unit test for the property 'FrameTime'
        }
        /// <summary>
        /// Test the property 'PathPosition'
        /// </summary>
        [Test]
        public void PathPositionTest()
        {
            // TODO unit test for the property 'PathPosition'
        }
        /// <summary>
        /// Test the property 'CameraOrientation'
        /// </summary>
        [Test]
        public void CameraOrientationTest()
        {
            // TODO unit test for the property 'CameraOrientation'
        }
        /// <summary>
        /// Test the property 'LiftAngle'
        /// </summary>
        [Test]
        public void LiftAngleTest()
        {
            // TODO unit test for the property 'LiftAngle'
        }

    }

}
