/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Color
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ColorTests
    {
        // TODO uncomment below to declare an instance variable for Color
        //private Color instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Color
            //instance = new Color();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Color
        /// </summary>
        [Test]
        public void ColorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Color
            //Assert.IsInstanceOfType<Color> (instance, "variable 'instance' is a Color");
        }


        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Test]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }
        /// <summary>
        /// Test the property 'G'
        /// </summary>
        [Test]
        public void GTest()
        {
            // TODO unit test for the property 'G'
        }
        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Test]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }
        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Test]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }

    }

}
