/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DamageData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DamageDataTests
    {
        // TODO uncomment below to declare an instance variable for DamageData
        //private DamageData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DamageData
            //instance = new DamageData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DamageData
        /// </summary>
        [Test]
        public void DamageDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DamageData
            //Assert.IsInstanceOfType<DamageData> (instance, "variable 'instance' is a DamageData");
        }


        /// <summary>
        /// Test the property 'FrameTimeStart'
        /// </summary>
        [Test]
        public void FrameTimeStartTest()
        {
            // TODO unit test for the property 'FrameTimeStart'
        }
        /// <summary>
        /// Test the property 'FrameTimeEnd'
        /// </summary>
        [Test]
        public void FrameTimeEndTest()
        {
            // TODO unit test for the property 'FrameTimeEnd'
        }
        /// <summary>
        /// Test the property 'InspectionNorm'
        /// </summary>
        [Test]
        public void InspectionNormTest()
        {
            // TODO unit test for the property 'InspectionNorm'
        }
        /// <summary>
        /// Test the property 'PathPosition'
        /// </summary>
        [Test]
        public void PathPositionTest()
        {
            // TODO unit test for the property 'PathPosition'
        }
        /// <summary>
        /// Test the property 'RangeDamageCode'
        /// </summary>
        [Test]
        public void RangeDamageCodeTest()
        {
            // TODO unit test for the property 'RangeDamageCode'
        }
        /// <summary>
        /// Test the property 'MajorCode'
        /// </summary>
        [Test]
        public void MajorCodeTest()
        {
            // TODO unit test for the property 'MajorCode'
        }
        /// <summary>
        /// Test the property 'Characterization1'
        /// </summary>
        [Test]
        public void Characterization1Test()
        {
            // TODO unit test for the property 'Characterization1'
        }
        /// <summary>
        /// Test the property 'Characterization2'
        /// </summary>
        [Test]
        public void Characterization2Test()
        {
            // TODO unit test for the property 'Characterization2'
        }
        /// <summary>
        /// Test the property 'Quantification1'
        /// </summary>
        [Test]
        public void Quantification1Test()
        {
            // TODO unit test for the property 'Quantification1'
        }
        /// <summary>
        /// Test the property 'Quantification2'
        /// </summary>
        [Test]
        public void Quantification2Test()
        {
            // TODO unit test for the property 'Quantification2'
        }
        /// <summary>
        /// Test the property 'PerimeterLocation1'
        /// </summary>
        [Test]
        public void PerimeterLocation1Test()
        {
            // TODO unit test for the property 'PerimeterLocation1'
        }
        /// <summary>
        /// Test the property 'PerimeterLocation2'
        /// </summary>
        [Test]
        public void PerimeterLocation2Test()
        {
            // TODO unit test for the property 'PerimeterLocation2'
        }
        /// <summary>
        /// Test the property 'Connection'
        /// </summary>
        [Test]
        public void ConnectionTest()
        {
            // TODO unit test for the property 'Connection'
        }

    }

}
