/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DetectionState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DetectionStateTests
    {
        // TODO uncomment below to declare an instance variable for DetectionState
        //private DetectionState instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DetectionState
            //instance = new DetectionState();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DetectionState
        /// </summary>
        [Test]
        public void DetectionStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DetectionState
            //Assert.IsInstanceOfType<DetectionState> (instance, "variable 'instance' is a DetectionState");
        }


        /// <summary>
        /// Test the property 'DetectionClass'
        /// </summary>
        [Test]
        public void DetectionClassTest()
        {
            // TODO unit test for the property 'DetectionClass'
        }
        /// <summary>
        /// Test the property 'PathPosition'
        /// </summary>
        [Test]
        public void PathPositionTest()
        {
            // TODO unit test for the property 'PathPosition'
        }
        /// <summary>
        /// Test the property 'DetectionId'
        /// </summary>
        [Test]
        public void DetectionIdTest()
        {
            // TODO unit test for the property 'DetectionId'
        }
        /// <summary>
        /// Test the property 'PathPositionMin'
        /// </summary>
        [Test]
        public void PathPositionMinTest()
        {
            // TODO unit test for the property 'PathPositionMin'
        }
        /// <summary>
        /// Test the property 'PathPositionMax'
        /// </summary>
        [Test]
        public void PathPositionMaxTest()
        {
            // TODO unit test for the property 'PathPositionMax'
        }
        /// <summary>
        /// Test the property 'ClockPositionMin'
        /// </summary>
        [Test]
        public void ClockPositionMinTest()
        {
            // TODO unit test for the property 'ClockPositionMin'
        }
        /// <summary>
        /// Test the property 'ClockPositionMax'
        /// </summary>
        [Test]
        public void ClockPositionMaxTest()
        {
            // TODO unit test for the property 'ClockPositionMax'
        }
        /// <summary>
        /// Test the property 'InspectionCode'
        /// </summary>
        [Test]
        public void InspectionCodeTest()
        {
            // TODO unit test for the property 'InspectionCode'
        }
        /// <summary>
        /// Test the property 'C1'
        /// </summary>
        [Test]
        public void C1Test()
        {
            // TODO unit test for the property 'C1'
        }
        /// <summary>
        /// Test the property 'C2'
        /// </summary>
        [Test]
        public void C2Test()
        {
            // TODO unit test for the property 'C2'
        }

    }

}
