/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GuiDetectionColorBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GuiDetectionColorBodyTests
    {
        // TODO uncomment below to declare an instance variable for GuiDetectionColorBody
        //private GuiDetectionColorBody instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GuiDetectionColorBody
            //instance = new GuiDetectionColorBody();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GuiDetectionColorBody
        /// </summary>
        [Test]
        public void GuiDetectionColorBodyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GuiDetectionColorBody
            //Assert.IsInstanceOfType<GuiDetectionColorBody> (instance, "variable 'instance' is a GuiDetectionColorBody");
        }


        /// <summary>
        /// Test the property 'DetectionClass'
        /// </summary>
        [Test]
        public void DetectionClassTest()
        {
            // TODO unit test for the property 'DetectionClass'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

    }

}
