/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GuiDetectionColorBody1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GuiDetectionColorBody1Tests
    {
        // TODO uncomment below to declare an instance variable for GuiDetectionColorBody1
        //private GuiDetectionColorBody1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GuiDetectionColorBody1
            //instance = new GuiDetectionColorBody1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GuiDetectionColorBody1
        /// </summary>
        [Test]
        public void GuiDetectionColorBody1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GuiDetectionColorBody1
            //Assert.IsInstanceOfType<GuiDetectionColorBody1> (instance, "variable 'instance' is a GuiDetectionColorBody1");
        }


        /// <summary>
        /// Test the property 'DetectionClass'
        /// </summary>
        [Test]
        public void DetectionClassTest()
        {
            // TODO unit test for the property 'DetectionClass'
        }
        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Test]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

    }

}
