/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InspectionNorm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InspectionNormTests
    {
        // TODO uncomment below to declare an instance variable for InspectionNorm
        //private InspectionNorm instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InspectionNorm
            //instance = new InspectionNorm();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InspectionNorm
        /// </summary>
        [Test]
        public void InspectionNormInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InspectionNorm
            //Assert.IsInstanceOfType<InspectionNorm> (instance, "variable 'instance' is a InspectionNorm");
        }


        /// <summary>
        /// Test the property 'ExchangeFormat'
        /// </summary>
        [Test]
        public void ExchangeFormatTest()
        {
            // TODO unit test for the property 'ExchangeFormat'
        }
        /// <summary>
        /// Test the property 'CodeSystem'
        /// </summary>
        [Test]
        public void CodeSystemTest()
        {
            // TODO unit test for the property 'CodeSystem'
        }

    }

}
