/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InspectionRunStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InspectionRunStatusTests
    {
        // TODO uncomment below to declare an instance variable for InspectionRunStatus
        //private InspectionRunStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InspectionRunStatus
            //instance = new InspectionRunStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InspectionRunStatus
        /// </summary>
        [Test]
        public void InspectionRunStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InspectionRunStatus
            //Assert.IsInstanceOfType<InspectionRunStatus> (instance, "variable 'instance' is a InspectionRunStatus");
        }


        /// <summary>
        /// Test the property 'FrameTime'
        /// </summary>
        [Test]
        public void FrameTimeTest()
        {
            // TODO unit test for the property 'FrameTime'
        }
        /// <summary>
        /// Test the property 'RunningState'
        /// </summary>
        [Test]
        public void RunningStateTest()
        {
            // TODO unit test for the property 'RunningState'
        }

    }

}
