/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Orientation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrientationTests
    {
        // TODO uncomment below to declare an instance variable for Orientation
        //private Orientation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Orientation
            //instance = new Orientation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Orientation
        /// </summary>
        [Test]
        public void OrientationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Orientation
            //Assert.IsInstanceOfType<Orientation> (instance, "variable 'instance' is a Orientation");
        }


        /// <summary>
        /// Test the property 'RotationAngle'
        /// </summary>
        [Test]
        public void RotationAngleTest()
        {
            // TODO unit test for the property 'RotationAngle'
        }
        /// <summary>
        /// Test the property 'TiltAngle'
        /// </summary>
        [Test]
        public void TiltAngleTest()
        {
            // TODO unit test for the property 'TiltAngle'
        }
        /// <summary>
        /// Test the property 'PanAngle'
        /// </summary>
        [Test]
        public void PanAngleTest()
        {
            // TODO unit test for the property 'PanAngle'
        }

    }

}
