/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SectionBaseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SectionBaseDataTests
    {
        // TODO uncomment below to declare an instance variable for SectionBaseData
        //private SectionBaseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SectionBaseData
            //instance = new SectionBaseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SectionBaseData
        /// </summary>
        [Test]
        public void SectionBaseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SectionBaseData
            //Assert.IsInstanceOfType<SectionBaseData> (instance, "variable 'instance' is a SectionBaseData");
        }


        /// <summary>
        /// Test the property 'SectionId'
        /// </summary>
        [Test]
        public void SectionIdTest()
        {
            // TODO unit test for the property 'SectionId'
        }
        /// <summary>
        /// Test the property 'Diameter'
        /// </summary>
        [Test]
        public void DiameterTest()
        {
            // TODO unit test for the property 'Diameter'
        }
        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Test]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }
        /// <summary>
        /// Test the property 'Material'
        /// </summary>
        [Test]
        public void MaterialTest()
        {
            // TODO unit test for the property 'Material'
        }
        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Test]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

    }

}
