/* 
 * SaridaEdgeAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WebHookProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WebHookPropertiesTests
    {
        // TODO uncomment below to declare an instance variable for WebHookProperties
        //private WebHookProperties instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WebHookProperties
            //instance = new WebHookProperties();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WebHookProperties
        /// </summary>
        [Test]
        public void WebHookPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WebHookProperties
            //Assert.IsInstanceOfType<WebHookProperties> (instance, "variable 'instance' is a WebHookProperties");
        }


        /// <summary>
        /// Test the property 'ServiceURI'
        /// </summary>
        [Test]
        public void ServiceURITest()
        {
            // TODO unit test for the property 'ServiceURI'
        }

    }

}
